//@@include('./options.js')

//@@include('./components/soundManager.js')
//@@include('./components/input.js')
//@@include('./components/utils.js')
//@@include('./components/gameFunc.js')
//@@include('./components/gui.js')

//@@include("./gameObjects/thorn.js")
//@@include("./gameObjects/coin.js")
//@@include("./gameObjects/movableThorn.js")
//@@include('./gameObjects/player.js')
//@@include('./gameObjects/exitDoor.js')
//@@include('./gameObjects/led.js')
//@@include('./gameObjects/mine.js')
//@@include('./gameObjects/error01.js')
//@@include('./gameObjects/doorSensor.js')
//@@include('./gameObjects/screenA.js')
//@@include('./gameObjects/platform01.js')
//@@include('./gameObjects/arrow.js')

//@@include('./components/gameObjectFactory.js')
//@@include('./components/world.js')

//@@include('./states/boot.js')
//@@include('./states/preload.js')
//@@include('./states/story.js')
//@@include('./states/menu.js')
//@@include('./states/waitDecodeAudio.js')

//@@include('./components/state.js')
//@@include('./states/levels/level1.js')
//@@include('./states/levels/level2.js')
//@@include('./states/levels/level3.js')
//@@include('./states/levels/level4.js')
//@@include('./states/levels/level5.js')
//@@include('./states/levels/level6.js')
//@@include('./states/levels/level7.js')
//@@include('./states/levels/level8.js')
//@@include('./states/levels/level9.js')
//@@include('./states/levels/level10.js')


//@@include('./states/test.js')

