//@@include('./options.js')

//@@include('./components/soundManager.js')
//@@include('./components/input.js')
//@@include('./components/utils.js')

//@@include("./gameObjects/thorn.js")
//@@include("./gameObjects/coin.js")
//@@include("./gameObjects/movableThorn.js")
//@@include('./gameObjects/player.js')
//@@include('./gameObjects/exitDoor.js')
//@@include('./gameObjects/led.js')
//@@include('./gameObjects/mine.js')
//@@include('./gameObjects/error01.js')
//@@include('./gameObjects/fan01.js')
//@@include('./gameObjects/doorSensor.js')
//@@include('./gameObjects/screenA.js')
//@@include('./gameObjects/screenD.js')
//@@include('./gameObjects/platform01.js')

//@@include('./components/gameObjectFactory.js')

//@@include('./states/boot.js')
//@@include('./states/preload.js')
//@@include('./states/story.js')
//@@include('./states/menu.js')
//@@include('./states/waitDecodeAudio.js')
//@@include('./states/play.js')

//@@include('./states/test.js')